---
title: "R Notebook"
output: html_notebook
---
Job satisfaction within entry level programs and implications for the APS Workforce Strategy 2025:
Analysis of APS employee attitudes and retention rates using the 2021 APS Census


SOCR3001 Assignment 3
31/05/2022
u7116787

Introduction
The Australian Public Service (APS) has recently undergone workforce reviews and strategy development in response to a rapidly evolving job market. Despite their significant reliance on entry-level recruitment strategies, such as graduate, trainee, and internship programs, for external recruiting, there is yet to be an independent verification of their efficacy. 

The aim of this paper is to analyse the attitudes and job satisfaction of participants of entry-level programs and to produce a preliminary evaluation on whether these programs are retaining talent. It is not within the scope of this essay to perform a policy evaluation as it would require further data collection and research into the causal mechanisms behind the programs. However, the insights generated by this paper may inform future policy evaluations and re-designs of grad/ trainee/ internship programs.

First, the paper will provide context on the current state of the APS and highlight why it is important to validate the performance of entry-level programs to inform future recruitment strategies. After outlining the motivating research questions, it will then evaluate the strengths and weaknesses of the APS 2021 census data before describing the research method. Overall, it finds that participants generally have a positive view on working in their current role however identifies a lack of growth opportunities as a pressure point. Policy should address this by identifying and rectifying the specific issues which may cause this behaviour. Additionally, as the analysis found that the program participants have significantly different attitudes and values to mid-senior level professionals, further investigations into the career values of mid and senior level professionals should be done as tailoring a recruitment strategy will be more effective than just modelling one of the existing entry-level programs.

Context and Literature Review
The APS’ performance as a workforce is essential in providing good, essential services to the Australian Government, Parliament, and people. In 2019, they underwent an independent review where it was identified that the “APS needs a service-wide transformation to achieve better outcomes”. One of the key priorities was to invest in capability and talent development. An identified barrier was the overreliance on internal hiring with 92% of promotions in the APS being internal to the agency and over 25% of external SES hires leaving within 2 years. External hiring is an important human resource practice as it leads to the growth of the skills and attitudes of the workforce. As a the only systematic search for external hires occurred at the graduate/ trainee/ internship level, one of their recommendations was:

“Annual external recruitment at EL and SES levels, modelled on the approach to graduates, to reduce barriers to entry from outside the APS.”

As a response, the Australian Public Skills Commission (APSC) released an action plan where one of the proposed actions is to “Attract, build and retain skills, expertise and talent”. The action plan echoed the same sentiment of using the graduate recruitment program to inform the design of an APS wide mid-level professional recruitment strategy. 

Despite the entry-level programs being described as the only systematic external hiring strategy, there is a lack of independent reviews validating the efficacy of these programs. Understanding the grad/ trainee programs strengths and weaknesses is crucial for informing future action plans (such as the mid-level recruiting strategy) and crucial for justifying the high investment costs these programs carry. 

The wider literature emphasises the need for specific investigations for specific implementations of HR strategies. While the literature does identify recurring common factors for retention, such as compensation and opportunity to grow, these general assumptions are not sufficient for designing an effective program; the context of the job and the attributes of the target group significantly influences which strategies the target employee will and won’t  respond to.

The existing, publicly available evaluations are limited to short case studies which are potentially biassed and lack any nuanced investigation into the program itself. For example, while the conclusion of the case study of the establishment of APSJobs was positive, an increase of grad applications by 37%, the conclusion doesn’t address the important outcomes necessary for a successful workforce, namely attracting the good talent, developing the skills of workers, and having a high retaining rate. Additionally, conflicting accounts of the success of the grad programs, such as the submission to PMC criticising its shortcomings providing effective skills training to the participants, highlight the strong need for an independent analysis of these programs. 

This paper aims to contribute to the evaluation of current graduate, trainee, and internship programs by focusing on one of the relevant outcomes, retention rate, by using job satisfaction as a proxy measurement. Existing literature justifies the use of job satisfaction as it is strongly correlated with employee retention rate.

Research Questions
As outlined in the literature review, this paper’s analysis is motivated by the recommendation to use the current implementation of the graduate/ entry-level programs to design future mid-senior level recruitment strategies. This paper is interested in challenging two assumptions behind this recommendation:
Are current entry-level recruitment programs effective in retaining talent? Even if the programs are effective in attracting and developing the right talent, it would be detrimental to model future recruitment strategies off a program that has a high employee turnover rate.
What insights from a program targeting entry-level talent could be useful for designing a similar program for a different target population (mid or senior level professionals)? 
These questions are not sufficient for making a judgement of the success of entry-level programs or providing justified policy advice on future workforce strategies. However, challenging the assumptions the 2025 workforce strategy operates on  are necessary steps to enacting a data informed action plan. 

Strengths and Limitations of the Dataset
The analysis uses the 2021 APS census; it is designed by the APSC to measure the attitudes and behaviours of the APS employees and is collected via an online questionnaire yearly. This paper will now assess the dataset’s strengths and weaknesses in addressing the research question and producing valid analysis by analysing it against the total survey error framework.

Ability to address the research question
This dataset is very useful for answering the research question outlined in this paper; this is in part due to the dataset informing the development of the research questions. The focus on analysing job satisfaction and employee attitude aligns with how Section B (general impression of the current job) was designed (with influence from general HR literature). 

However a weakness of the dataset is that a survey is ridged by nature and requires quite structured responses. While this is more cost effective, further qualitative studies could be done to investigate the causal mechanisms that positively and negatively affect both the entry-level program and the job satisfaction of the participant. 

Another weakness is that the dataset only contains a slice of time. This is particularly influential as 2021 could be seen as an outlier year. While the census is done yearly, the data is not linked. To do a policy evaluation, a longitudinal study measuring the impacts of the early-entry program (like a treatment) could quantitatively assess the success of the programs.


Reliability of analysis
Overall, the survey was designed well. As it is a census, it minimises coverage and sampling error. It has a response rate of 77% which is relatively high in comparison to other state’s surveys which had  response rates ranging from 22-46%. This lowers the risk of non-response error. A common introduction of non-response error for online surveys, not representing people without access to digital technologies, is not relevant as the population, APS workers,  should all have access to technology. Even if there is non-response error, a significant proportion of the population is being represented with 109537 survey participants from 101 different agencies. 

There is a risk of measurement error particularly as respondents may (knowingly or unknowingly) lie for certain questions in the survey. The risk of this is relatively low as the census is anonymous and was advertised as being a way for the individual to communicate their positive and negative experience, incentivising truth. Overall, it is still important to identify this as a potential source of error particulate for sensitive or high stakes questions. 

The more influential dataset weakness is the anonymisation of the dataset. This paper agrees that the anonymisation was necessary particularly as it was publicly available unaggregated data. However, the anonymisation method included the aggregation of the categories trainee, graduate, and the levels aps 1-6 into one category. This meant that the paper had to make assumptions on who is a participant of an entry level program (typically trainees, graduates, and APS1-3). The assumption this paper holds is not very strong which has severe negative validity implications for this paper which may need to be addressed with further research studies and access to data.

Overall, the strengths of the dataset is its robustness to the introduction of error due to its good design and the design of the questions aligning with the paper’s research questions. The weakness of the dataset is its narrow scope both with information that can be collected and the specific time that it recommends - this can be addressed with supplementary longitudinal studies and qualitative data collection. The most severe weakness is that the dataset does not explicitly identity our target population which means that this paper will have to operate on assumptions which the next section will assess.

Method
The methodology of the analysis can be categorised into four main steps:
Preprocessing
Preprocessing entails the subsetting of the relevant parts of the data. This includes the answers to Section B alongside some other interesting questions. The main assumption made in this step is using APS 1-6 and age <40 as a heuristic to predict which individuals are participants of entry-level programs. 

The intended target population is trainees, graduates, and APS 1-3. However this heuristic over-samples the target population; ignoring the age filter, the target population only accounts for 23% of the population that we are sampling. This would significantly impact the validity of findings; rather than representing entry-level program employees, the analysis represents early stage professionals. This paper acknowledges this error however holds the egregious assumption however for the sake of the assignment noting that this analysis of this paper could be redone with the un-aggregated data. 

Generate summary statistics
Use percentage frequency to analyse the grad/intern/trainee population’s  distribution of positive and negative attitudes towards different aspects of their workplace. This contributes to answering research question 1 by measuring:
Do employees from the target population show signs of high job satisfaction? 
We use these findings to infer whether employee turnover is likely to be high
Which areas are they more/ less satisfied  in? 
This may indicate potential strengths and weaknesses of the program or different values.

Fit a regression model 
By fitting a generalised linear model on the data, the paper can use the summary table to identify predictors that significantly contribute to explaining the likelihood of an employee leaving. This addresses RQ 1 by answering the subquestion:
Specifically which workplace attributes contribute most to job satisfaction/ dissatisfaction / wanting to leave?

Then, a secondary model is fitted on the comparative sample which consists of the rest of the APS workers. This is the start of addressing RQ 2 as it asks the subquestion:
Are there distinct differences between the entry-level program population and the mid/senior? Do they have different values and motivations to work?

This step makes a few assumptions over the validity of the modelling process particularly as the focus of the analysis was not to fit a useful predictor but to analyse which predictive variables significantly explained 

Use statistical testing to compare the summary statistics of the program participant 
A further comparison for the entry-level employees to the rest of the APS population: statistical t-tests applied to the summary statistics generated from step 2. Additionally, a comparative analysis of the most common reasons for leaving the APS for both populations will be done using a frequency table.

Overall assumptions that this method relies on is the relationship between job satisfaction and retention rate. While the literature justifies this assumption, it is important to remember that these two metrics, while heavily correlated,  measure distinct outcomes. 

Main Findings
Overall, the method was followed and the outcome of the analysis is documented in the appendix. This section of the paper will now present the key takeaways from the analysis.
Program participants had a generally positive attitude towards their work. 

For participants The aspects with the highest and lower satisfaction rates mirrored existing public servant stereotypes 
Within program participants, the aspects that had higher satisfaction rates align with the concept of public servant altruism, however aspects that hd lower satisfaction rates were remuneration and ‘my work inspires me’

For the target group, the top three most significant predictors for planning to leave included (in order from high t-value to low); job satisfaction, job inspires me, satisfied with stability and security, 

When comparing the fitted GLM of the target population (participants) and the alternate population (rest of the APS), the alternate population had more significant predictors

When comparing the attitudes towards the current job of the target and comparison population, many are statistically significant due to the high sample size. However, there were noticeably large differences in the distribution of 17e and 17f (and then 17g and 17l)

The two populations differ in the common reasons for wanting to leave. Focus on development vs team and leadership culture 


Policy Implications and Discussion
The findings can be summarised into three key policy implications 
On average, the peps seem to have a positive attitude towards working in their current jobs. The most positive sentiments do align with the literature and the concept of public servant altruism
However, for the people that do decide to leave, a lack of growth opportunities appears to a significant motivator for entry level people in leaving the APS
There appeared to be different motivations between the entry-level program professionals and the rest. Particularly as this paper doesn’t make a clear distinction between.. (assumption) the implication is that <INSERT>

Overall this paper has shown that programs seem to be working, but differences in the population may mean it won’t be effective for mid/senior professional recruitment strategies. Although the strengths of this paper was that it addressed an important gap in the evaluation of the APS using a representative dataset, limitations of the dataset caused significant weaknesses in the analysis; namely the incorrect inclusion of APS non-entry-level program employees in the analysis due to aggregation and inability to study mechanisms which is needed to make general causal claims due to the limitations of the data.
To address these weaknesses, future analysis should 
Run the analysis on data that specifically identifies employees under the early entry programs
Include a longitudinal measurement to justify causal claims on the efficacy of the recruitment program
include qualitative focus groups to further investigate causal mechanics and address RQ 4-7
The topic of APS recruitment is important to understand as the quality of their services are so important for upholding the quality of Australians lives. 

Conclusion 
Overall, this paper has used a subsection of the 2021 APS census to analyse patterns in the attitudes of employees (who are assumed to be) in an entry-level program such as the APS graduate program. The key takeaway from this analysis is that overall, participants of the program


Bibliography
2019. APS Review: Graduate Programs. [ebook] Available at: <https://www.apsreview.gov.au/file/182/fil038500d6640b2fa11305c.pdf?token=L4bbztww> [Accessed May 2022].
2021. Delivering for Tomorrow: APS Workforce Strategy 2025. Commonwealth of Australia.
Australian Public Service Commission, 2021. APS Employee Census 2021 [data set], APSC website.
Australian Public Service Commission, 2021. Australian Public Service Employee Census Explanatory Guide 2021. Canberra.
Australian Public Service Commission, 2021. State of the Service Report 2020–21. Commonwealth of Australia.
Das, B., 2013. Employee Retention: A Review of Literature. IOSR Journal of Business and Management, 14(2), pp.08-16.
Department of the Prime Minister and Cabinet, 2019. Our Public Service Our Future: Independent Review of the Australian Public Service. Commonwealth of Australia.
Department of the Prime Minister and Cabinet, 2021. Independent Review of the APS: Priorities for Change. Commonwealth of Australia.
Taylor, J., 2005. Recruiting university graduates for the public sector: an Australian case study. International Journal of Public Sector Management, 18(6), pp.514-533.

